### PR TITLE
API Route: Trip Booking

### LINKED ISSUE #69: Create API route for trip booking
## Book trip
API route: `/api/trip/booking`
- [x]  startPlace
- [x] endPlace
- [x] startTime
- [x] ac - ac{1} or non-ac{0}
- [x] vehicleType -  taxi{1} or private/rental{0}
- [x] token

### PR DESCRIPTION
**Pull request by malivinayak**
Created 5 different triggers and fired multiple insert, update, select queries for single trip booking
Closes #69

### CODE REVIEW

**Comment by malivinayak** [comment]
@OutdatedGuy Route is tested with front end
**Created 5 different triggers and fired multiple insert, update, select queries for single trip booking**
Took**more than 6 hours** to create just single trip booking route

**Review by patilprthm — APPROVED** [review]
Approved by Vinayak

**Comment by malivinayak** [comment]
@OutdatedGuy Check this PR and let me know for needful changes

**Comment by OutdatedGuy** [comment]
LGTM!

**Pull request merged**
