### PR TITLE
Editing issue-message

### PR DESCRIPTION
**Pull request by malivinayak**
# workflow-enhancement 
**Making issue-message more interactive**

### CODE REVIEW

**Comment by malivinayak** [comment]
@Pratham1402 @OutdatedGuy 
I have implemented GitHub workflow for some automated stuff
Kindly review the changes made an approve it if everything is ok

**Review by OutdatedGuy — APPROVED** [review]
LGTM!

**Comment by OutdatedGuy** [comment]
Remember, whenever you merge PRs, do it as "Squash and merge" rather than just plain merge.

**Comment by malivinayak** [comment]
> Remember, whenever you merge PRs, do it as "Squash and merge" rather than just plain merge.

Definitely

**Comment by malivinayak** [comment]
I am keeping this branch to. 
If any workflow related enhancement you have then utilize this branch

**Comment by OutdatedGuy** [comment]
> I am keeping this branch to. If any workflow related enhancement you have then utilize this branch

That won't do, delete branches after merging PRs as this branch and main branch won't be having same routes.
So there would be unnecessary merge conflicts and merge commit messages.

We can always create the new branch with same name.

**Comment by malivinayak** [comment]
> That won't do, delete branches after merging ....


I am trying to develop a GitHub workflow which can automatically update other branch once any PR is made on main branch
Just for sec of learning purpose
We will definitely delete this branch whether the workflow is created or not

If you already know such workflow/ GitHub action then let me know

**Comment by malivinayak** [comment]
Deleting workflow-enhancement branch to avoid unnecessary merging commits

**Pull request merged**
